# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install
        run: sudo apt-get install -y shellcheck doxygen
      - name: Tests
        run: make audit
      - name: Doc
        run: make doc-package
      - name: Build
        run: make package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpm-manager.tar.gz
            rpm-manager-doc.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
