# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare build container
        run: docker build --tag rpmmanager/dev --file containers/dev.Dockerfile  .
      - name: Build
        run: |
          docker run --rm -e "GNUPGHOME=/tmp" -v "$(pwd):/mnt" -u "$(id -u ${USER}):$(id -g ${USER})" rpmmanager/dev make all
      - name: Save coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
      - name: Build experimental release container
        run: |
          docker build -f containers/Dockerfile -t rpm-manager/rpm-manager .
          docker run --rm rpm-manager/rpm-manager
      - name: Generate release message
        run: |
          awk -e '/^## /{a+=1} {if(a==1)print$0}' CHANGELOG.md >CHANGELOG.release.md
      - name: Release to github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.release.md
          files: |
            rpm-manager.tar.gz
            rpm-manager-doc.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
